/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BogdanRouterV2__factory } from "./BogdanRouterV2__factory";
export { BogdanRouterV3__factory } from "./BogdanRouterV3__factory";
