/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UniswapV2Pair__factory } from "./UniswapV2Pair__factory";
export { UniswapV2PairC__factory } from "./UniswapV2PairC__factory";
