/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BogdanRouterV2 } from "./BogdanRouterV2";
export type { BogdanRouterV3 } from "./BogdanRouterV3";
